# Generated by Django 4.0 on 2021-12-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprachwebseite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
