# Generated by Django 4.0 on 2021-12-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprachwebseite', '0002_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Course Name')),
                ('teacher', models.CharField(max_length=60, verbose_name='Course Name Teacher')),
                ('date', models.DateTimeField(max_length=60, verbose_name='Course Date')),
                ('language', models.CharField(max_length=60, verbose_name='Course Language')),
                ('languagelvl', models.CharField(max_length=60, verbose_name='Course level')),
                ('coursetype', models.CharField(max_length=60, verbose_name='Course Type')),
                ('info', models.TextField(blank=True, verbose_name='Course Info')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60, verbose_name='First Name')),
                ('lname', models.CharField(max_length=60, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=60, verbose_name='User Email')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='course',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sprachwebseite.members'),
        ),
    ]
