# Generated by Django 4.0 on 2021-12-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprachwebseite', '0003_course_members_delete_member_course_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
    ]
