# Generated by Django 4.0 on 2021-12-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprachwebseite', '0004_remove_course_contact_remove_course_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Teacher Email'),
        ),
    ]
