# Generated by Django 4.0 on 2021-12-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprachwebseite', '0005_course_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
