# Generated by Django 4.0 on 2021-12-13 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sprachwebseite', '0006_delete_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
