# Generated by Django 4.0 on 2021-12-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprachwebseite', '0008_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(max_length=60, null=True, verbose_name='Course Name Teacher'),
        ),
    ]
